apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kafka
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-kafka:v0.5.0
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: crossplane-contrib-function-go-templating
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.8.0
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-auto-ready
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.2.1
